apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolov5-deployment
  labels:
    app: yolov5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolov5
  template:
    metadata:
      labels:
        app: yolov5
    spec:
      containers:
      - name: yolov5-server
        image: registry.cn-hangzhou.aliyuncs.com/fishing01/fastapi-yolov5
        ports:
        - containerPort: 8000
