apiVersion: v1
kind: Service
metadata:
  name: yolov5
spec:
  type: NodePort
  selector:
    app: yolov5
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 32143
